### ISSUE TITLE
originator of 'RLum.Analysis' objects produced by 'model_LuminescenceSignals()'

### ISSUE THREAD

**Issue by tzerk** [R-Lum/RLumModel#10]
The originator of `RLum.Analysis` produced by 'model_LuminescenceSignals()' is set to `.translate_sequence()`. Shouldn't it rather be 'model_LuminescenceSignals()', as `.translate_sequence()` is only one of the several subroutines? 

If so, the originator should probably be hardcoded here:
https://github.com/R-Lum/RLumModel/blob/master/R/translate_sequence.R#L276

**Comment by RLumSK** [comment]
Still open?

**Comment by JohannesFriedrich** [comment]
No, it was hardcoded, as suggested by @tzerk.

Close
