### ISSUE TITLE
Move back to R.rsp for vignette building

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/RLumModel#12]
I suggest to move back to `R.rsp` for the vignettes to get rid of the warnings
on [CRAN](https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/RLumModel-00check.html)

**Comment by JohannesFriedrich** [comment]
The problem should be easily solved adding `rmarkdown` to SUGGESTS in DESCRIPTION. I see no reason to switch back.

**Comment by RLumSK** [comment]
According to the error messages, `Pandoc (>= 1.12.3) and/or pandoc-citeproc not available.`, 
means, even we add `rmarkdown` to SUGGESTS it does not work.

**Comment by JohannesFriedrich** [comment]
Is it so important to remove the warning? 
Many other packages on CRAN also have it. It seem that pandoc is not compiled on the solaris machine CRAN tests on. That´s not surprising because there´s no manual on the pandoc website to compile it on solaris systems and it seems no that easy.

**Comment by RLumSK** [comment]
You are right, and as long CRAN is not complaining it is ok. In either case, your call, you are the maintainer. I just wanted to point that out.

**Comment by JohannesFriedrich** [comment]
Thanks for the hint, didn´t really know about the warning on the CRAN check.
