### ISSUE TITLE
Allow 0 s irradiation in 'sequence'

### ISSUE THREAD

**Issue by tzerk** [R-Lum/RLumModel#4]
In a SAR protocol the zero dose measurement (usually cycle R5) is often performed as an irradiation of 0 s length. However, the function fails when using the following:

```
RLumModel::model_LuminescenceSignals("Bailey2004", sequence = list(IRR = c(20, 0, 1)))
```

Of course, PAUSE would have the same effect, but I'd like to have the zero dose irradiation in the meta data of the RLum.Data.Curve object.

Error message:

```
Error in checkInput(y, times, func, rtol, atol, jacfunc, tcrit, hmin,  : 
  `hmax' must be a non-negative value
In addition: Warning message:
In max(abs(diff(times))) : no non-missing arguments to max; returning -Inf
```

**Comment by JohannesFriedrich** [comment]
Changed in 'simulate_irradiation'  and 'simulate_RF'
